checking output again

diff --git a/.github/workflows/robot-framework.yml b/.github/workflows/robot-framework.yml
--- a/.github/workflows/robot-framework.yml
+++ b/.github/workflows/robot-framework.yml
@@ -43,13 +43,13 @@ jobs:
           echo "MOZ_HEADLESS=1" >> $GITHUB_ENV
 
       - name: Run Robot Framework tests
-      run: |
-        robot --outputdir logs robot_automation/robot_basics
-        if [ $? -eq 0 ]; then  # Check the exit code of the previous command
-          echo -e "\e[32mTests passed!\e[0m"  # Set text color to green for pass
-        else
-          echo -e "\e[31mTests failed!\e[0m"  # Set text color to red for fail
-        fi
+        run: |
+          robot --outputdir logs robot_automation/robot_basics
+          if [ $? -eq 0 ]; then  # Check the exit code of the previous command
+            echo -e "\e[32mTests passed!\e[0m"  # Set text color to green for pass
+          else
+            echo -e "\e[31mTests failed!\e[0m"  # Set text color to red for fail
+          fi
 
       
       - name: Archive test results
